spring:
  application:
    name: lift_log
  datasource:
    url: jdbc:postgresql://localhost:5439/lift_log
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /

# JWT設定
jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  expiration: 24
