spring:
  application:
    name: lift_log
  datasource:
    url: ${DB_URL_DOCKER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

# JWT設定
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
